config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article)
    else
      redirect_to new_article_path
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h2>Edit article</h2>
<h2><--- * ---></h2>

<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<%= link_to "Back to Task List", articles_path, class: "btn btn-primary"%>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles Listing</h1>
  <% @articles.each do |article| %>
    <h2> <%= article.id %>. <%= link_to article.title, article_path(article), class: "link" %> <%= link_to '', article_path(article),
        method: :delete, class: "far fa-trash-alt"%> </h2>
    <p> <%= article.content %> </p>
  <% end %>

  <%= link_to "Add New Task", new_article_path, class: "btn btn-primary"%>
</div>

app/views/articles/new.html.erb
<ul class= "list-inline">
  <li class= "list-inline-item">
    <h2>Add Task</h2>
  </li>
  <li class= "list-inline-item">
    <%= link_to "Back to Article List", articles_path, class: "btn btn-primary"%>
  </li>
</ul>

<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.content %></p>

<ul class="list-inline">
  <li class="list-inline-item">
    <%= link_to "Edit Article", edit_article_path, class: "btn btn-primary"%>
  </li>
  <li class="list-inline-item">
    <%= link_to "Back to Article List", articles_path, class: "btn btn-primary"%>
  </li>
  <li class="list-inline-item">
    <%= link_to "Delete", article_path, method: :delete, class: "btn btn-danger"%>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>